[package]
name = "brew-uo"
version = "0.3.1"
authors = ["Hexin <hexium310@gmail.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
csv = "^1"
regex = "1"
version-compare = "0.0.10"
itertools = "0.8"
prettytable-rs = "0.8"
term_size = "0.3"
indoc = "0.3"
