[package]
name = "brew-uo"
version = "0.1.0"
authors = ["Hexin <hexium310@gmail.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
regex = "1"
version-compare = "0.0.8"
itertools = "0.8"
prettytable-rs = "0.8"
