combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2021"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
