name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout hexium310/brew-uo
        uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up a Rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --verbose
      - name: Pack
        run: |
          cd target/release
          tar zcvf macos.tar.gz brew-uo
          tar tf macos.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-tap:
    needs: release
    runs-on: macos-latest

    steps:
      - name: Update formula
        run: |
          brew tap hexium310/tap
          brew bump-formula-pr --version="${GITHUB_REF##*/}" hexium310/tap/brew-uo
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
